name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]



jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          repository: fredysomy/electron-auto-update
          ref: refs/heads/master
          path: electron-auto-update
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Replace electron with electron-nightly
        run: |
          cd electron-auto-update
          npm uninstall --save-dev electron
          npm install --save-dev electron-nightly@latest
        shell: bash
      - name: Install Electron Packager
        run: |
          cd electron-quick-start
          npm install --save-dev electron-packager@electron/electron-packager
      - name: Package
        run: |
          cd electron-quick-start
          node_modules/.bin/electron-packager . --arch=all
